### ISSUE TITLE
艾特人后，说不能买小真寻，咋回事啊 

### ISSUE THREAD

**Issue by BurstTNT** [CCYellowStar/zhenxun_plugin_slave_market#1]
艾特人后，说不能买小真寻，咋回事啊 
![%VI9QE8 3BWNK9`E}70}$13](https://github.com/CCYellowStar/zhenxun_plugin_slave_market/assets/136226428/c306bc92-33de-4560-a4e2-94d519086132)

**Comment by CCYellowStar** [comment]
你可能只是复制了名字没有at上

**Comment by idonotthinksoso** [comment]
同样问题， 应该是at上了

**Comment by CCYellowStar** [comment]
只是这一个人出问题吗

**Comment by RainSerein** [comment]
同样出了问题，@人加不加空格都不行
![)N_V2XXEK20R %7WIWBZ286](https://github.com/CCYellowStar/zhenxun_plugin_slave_market/assets/108612634/7842e5a3-5aba-4df2-8c0e-fb413a91a46d)
![NC0BB)0PTZ}0XH5CWK{_T9K](https://github.com/CCYellowStar/zhenxun_plugin_slave_market/assets/108612634/dff0d427-e3a4-49fb-b258-c8b60b296583)

**Comment by CCYellowStar** [comment]
> 同样出了问题，@人加不加空格都不行 ![)N_V2XXEK20R %7WIWBZ286](https://user-images.githubusercontent.com/108612634/248755987-7842e5a3-5aba-4df2-8c0e-fb413a91a46d.png) ![NC0BB)0PTZ}0XH5CWK{_T9K](https://user-images.githubusercontent.com/108612634/248756061-dff0d427-e3a4-49fb-b258-c8b60b296583.png)

报错看下

**Comment by CCYellowStar** [comment]
我好像知道了，你们是新版真寻

**Comment by CCYellowStar** [comment]
更新了

**Comment by idonotthinksoso** [comment]
更新了可以了

**Comment by RainSerein** [comment]
> 更新了

谢谢大佬，ღ( ´･ᴗ･` )比心
