### ISSUE TITLE
Unknown filter param 'user_id’

### ISSUE THREAD

**Issue by huihuiismywife** [CCYellowStar/zhenxun_plugin_slave_market#5]
如题，更新一下后就出现了这个报错了，之前还没事的![@}{$XKYTOZYB4MOMP9KCA04_tmb](https://github.com/CCYellowStar/zhenxun_plugin_slave_market/assets/107234845/07bdf4a6-3e70-40ea-a859-f341977fd5e6)

**Comment by youmingsama** [comment]
你数据库表应该还是之前的表，要不把之前建的表删掉，或者把__init__里面的user_id重新改回user_qq

**Comment by CCYellowStar** [comment]
真寻没更新，要不更新真寻要不就用这个插件的1.0，光光改数据库不行的
