### ISSUE TITLE
请问nonebot_plugin_imageutils这个库版本是多少

### ISSUE THREAD

**Issue by kuai364354200** [CCYellowStar/zhenxun_plugin_slave_market#9]
![图片](https://github.com/CCYellowStar/zhenxun_plugin_slave_market/assets/72508741/e4a7bbef-1822-4892-ba57-bfbd631b25f4)
07-28 01:09:12 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
{'time': 1690506552, 'self_id': 1504429250, 'post_type': 'message', 'sub_type': 'normal', 'user_id': 359258257, 'message_type': 'group', 'message_id': -66643489, 'message': [{'type': 'text', 'data': {'text': '购买群友'}}, {'type': 'at', 'data': {'qq': '1214373970'}}], 'original_message': [{'type': 'text', 'data': {'text': '购买群友'}}, {'type': 'at', 'data': {'qq': '1214373970'}}], 'raw_message': '购买群友[CQ:at,qq=1214373970]', 'font': 0, 'sender': {'user_id': 359258257, 'nickname': '禅', 'sex': 'unknown', 'age': 0, 'card': '感じる，感じる，全力です！', 'area': '', 'level': '', 'role': 'member', 'title': ''}, 'to_me': False, 'reply': None, 'group_id': 459529702, 'anonymous': None, 'message_seq': 1690973}
07-28 01:09:12 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main) running complete
07-28 01:09:12 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
07-28 01:09:12 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
07-28 01:09:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_github)
07-28 01:09:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_plugin_slave_market)
07-28 01:09:12 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_github) running complete
07-28 01:09:12 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“成”的字体
07-28 01:09:12 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“功”的字体
07-28 01:09:12 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“购”的字体
07-28 01:09:12 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“买”的字体
07-28 01:09:12 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“了”的字体
07-28 01:09:12 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“莱”的字体
07-28 01:09:12 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“瓦”的字体
07-28 01:09:12 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“汀”的字体
07-28 01:09:12 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“我”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“的”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“爱”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“人”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“！”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“！”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“花”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“费”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“了”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“1”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“金”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“币”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“，”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“还”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“剩”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“1”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“金”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“币”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“莱”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“瓦”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“汀”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“我”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“的”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“爱”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“人”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“！”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“获”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“得”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“了”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“1”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“金”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“币”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“，”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“现”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“在”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“拥”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“有”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“2”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“金”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“币”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“，”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“身”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“价”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“上”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“涨”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“1”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“-”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“>”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“1”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“2”的字体
07-28 01:09:13 [WARNING] nonebot_plugin_imageutils | 在当前字体列表中找不到可以显示字符“0”的字体
07-28 01:09:14 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_plugin_slave_market) running complete

**Comment by kuai364354200** [comment]
根据他的readme补充了ubuntu的字体
sudo apt install fonts-noto-cjk fonts-noto-color-emoji
sudo apt install fonts-noto
sudo locale-gen zh_CN zh_CN.UTF-8
sudo update-locale LC_ALL=zh_CN.UTF-8 LANG=zh_CN.UTF-8
fc-cache -fv
然后就好了。。。。

**Comment by kuai364354200** [comment]
![图片](https://github.com/CCYellowStar/zhenxun_plugin_slave_market/assets/72508741/b6957846-2838-443b-8130-7a4d93df40d5)
如果用nonebot-plugin-imageutils后台会报这些疑似错误？
根据他的readme把nonebot-plugin-imageutils改成了pil-utils，唯独购买群友时会出现方块字，不知道哪里的字体又少了
![图片](https://github.com/CCYellowStar/zhenxun_plugin_slave_market/assets/72508741/6f88047f-b9a3-438c-a2cd-3470ee29911d)
https://github.com/noneplugin/nonebot-plugin-imageutils

**Comment by CCYellowStar** [comment]
这个我也不清楚，我是Windows，你只能看看他的仓库里有没人人提到

**Comment by kuai364354200** [comment]
用初版的没事，不知道啥情况，先用着
